baseURL = 'https://bleedkagax.github.io/'
languageCode = 'en-us'
title = 'Kaga Blog'
theme = 'papermod'

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[menu]
  [[menu.main]]
    name = 'Posts'
    url = '/post/'
    weight = 10
  [[menu.main]]
    name = 'Categories'
    url = '/categories/'
    weight = 20
  [[menu.main]]
    name = 'Tags'
    url = '/tags/'
    weight = 30
  [[menu.main]]
    name = 'Archives'
    url = '/archives/'
    weight = 40
  [[menu.main]]
    name = 'Search'
    url = '/search/'
    weight = 50
[module]
  [[module.imports]]
    path = "github.com/hugomods/mermaid"
[params]
  mermaid = true
  ShowToc = true
  TocOpen = false





