baseURL = 'https://bleedkagax.github.io/'
languageCode = 'en-us'
title = 'Kaga Blog'
theme = 'papermod'

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[menu]
  [[menu.main]]
    name = 'Posts'
    url = '/post/'
    weight = 10
  [[menu.main]]
    name = 'Tags'
    url = '/tags/'
    weight = 20
  [[menu.main]]
    name = 'Archives'
    url = '/archives/'
    weight = 30
  [[menu.main]]
    name = 'Search'
    url = '/search/'
    weight = 40
[module]
  [[module.imports]]
    path = "github.com/hugomods/mermaid"
[params]
  mermaid = true
  ShowToc = true
  TocOpen = false

  [params.profileMode]
    enabled = true
    title = "Kaga Blog"
    subtitle = "Notes on engineering, systems, and learning."

    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/post/"
    [[params.profileMode.buttons]]
      name = "Archives"
      url = "/archives/"
    [[params.profileMode.buttons]]
      name = "Search"
      url = "/search/"





