baseURL = 'https://bleedkagax.github.io/'
languageCode = 'en-us'
title = 'Kaga Blog'
theme = 'papermod'
[module]
  [[module.imports]]
    path = "github.com/hugomods/mermaid"
[params]
  mermaid = true





